# Generated by Django 3.1.4 on 2020-12-13 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=17)),
                ('name', models.CharField(max_length=40)),
                ('num_peripherals', models.IntegerField()),
                ('device_type', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Peripheral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('num_params', models.IntegerField()),
                ('periph_type', models.IntegerField()),
                ('parent_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommandControl.device')),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('max_value', models.IntegerField()),
                ('value_type', models.IntegerField()),
                ('is_getable', models.BooleanField()),
                ('is_setable', models.BooleanField()),
                ('is_action', models.BooleanField()),
                ('parent_periph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CommandControl.peripheral')),
            ],
        ),
    ]
