# Generated by Django 3.1.4 on 2020-12-22 23:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='device_type',
            new_name='dev_type',
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='peripheral',
            name='periph_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
