# Generated by Django 3.1.4 on 2020-12-23 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0002_auto_20201222_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='CC/images'),
        ),
    ]
