# Generated by Django 3.1.4 on 2020-12-23 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0004_auto_20201223_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='static/CC/images/'),
        ),
    ]
