# Generated by Django 3.1.4 on 2020-12-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0005_auto_20201223_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='media/CC/images/'),
        ),
    ]
