# Generated by Django 3.1.4 on 2020-12-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0006_auto_20201224_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='image',
            field=models.ImageField(upload_to='CC/images/'),
        ),
    ]
