# Generated by Django 3.1.4 on 2020-12-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0007_auto_20201224_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peripheral',
            name='periph_image',
            field=models.ImageField(upload_to='CC/images/'),
        ),
    ]
