# Generated by Django 3.1.4 on 2020-12-24 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0008_auto_20201224_0441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheral',
            old_name='parent_device',
            new_name='device',
        ),
    ]
