# Generated by Django 3.1.4 on 2020-12-24 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CommandControl', '0009_auto_20201224_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parameter',
            old_name='parent_periph',
            new_name='peripheral',
        ),
    ]
